// import Brand from '@/components/ui/brand';
import Brand from "@/components/ui/brand";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthButton } from "@/components/auth/auth-button";
import { NextAuthProvider } from "@/components/providers/next-auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <header className="border-b">
            <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-2xl font-bold">
                <Brand />
              </h1>
              <AuthButton />
            </div>
          </header>
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
