// import Brand from '@/components/ui/brand';
import Brand from "@/components/ui/brand";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthButton } from "@/components/auth/auth-button";
import { NextAuthProvider } from "@/components/providers/next-auth-provider";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import { NavigationProgress } from "@/components/ui/navigation-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <NavigationProgress />
          <header className="border-b">
            <div className="container mx-auto px-4 py-4 flex justify-between items-center">
              <h1 className="text-2xl font-bold">
                <Link href="/">
                  <Brand />
                </Link>
              </h1>
              <AuthButton />
            </div>
            <Toaster />
          </header>
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
